<a href="https://colab.research.google.com/github/indranur/SLO/blob/main/GA_2101202069_Indra_Nurpratama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np 
import random
from array import *

In [45]:
daftarKota = [[45,25], [45,5], [30,20], [15,5], [15,20], [40, 10], [35,30], [25,10], [10,30], [5,10]]
for i in daftarKota:
    for j in i:
        print(j,end = " ")
    print()

jumlahKota =  len(daftarKota)   
print(jumlahKota)

45 25 
45 5 
30 20 
15 5 
15 20 
40 10 
35 30 
25 10 
10 30 
5 10 
10


In [46]:
def initPopulasi(ukuranPopulasi,jumlahKota):
  P = np.empty((ukuranPopulasi,jumlahKota))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahKota)
    for j in range(jumlahKota):
      P[i][j]=I[j]
  return P


ukuranPopulasi = 4
P = initPopulasi (ukuranPopulasi,jumlahKota)
print(P)

[[2 9 1 6 4 5 3 0 7 8]
 [0 5 9 6 2 1 8 4 7 3]
 [3 1 7 8 5 6 9 0 4 2]
 [7 2 0 5 4 6 1 9 3 8]]


In [47]:
def fungsiObjectif(populasi,daftarKota):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak  = matrikJarak.astype('float')
  n = len(daftarKota)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = daftarKota[populasi[i][j]][0]-daftarKota[populasi[i][j+1]][0]
      jrkY = daftarKota[populasi[i][j]][1]-daftarKota[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((daftarKota[populasi[i][n-1]][0]-daftarKota[populasi[i][0]][0])**2+ (daftarKota[populasi[i][n-1]][1]-daftarKota[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

fitP = fungsiObjectif(P,daftarKota)
print(fitP)
#print(fitP.dtype)

[277.36073072 234.83039887 277.68911658 221.00217053]


In [48]:
def seleksi (P,fsObj):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  Induk = np.empty((jmlInduk,jumlahKota))
  Induk = Induk.astype('int')
  
  for i in range (2):
    # memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahKota):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahKota):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

[[3 1 7 8 5 6 9 0 4 2]
 [0 5 9 6 2 1 8 4 7 3]]


In [49]:
#crossover 

def PMX(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]
  #print(sz, brs, kol)

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 

    Anak [0][i0] = Induk[0][i0]
    Anak [1][i0] = Induk[1][i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = Induk[0][i] 
    n2 = Induk[1][i]

    #mengecek apakah kota tertentu sudah ada di anak
    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol-1):
        idxAda1 = 1

      if Anak [0][j1] ==n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol-1):
        idxAda2 = 1

      if Anak [1][i0]  == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      Anak[0][batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      Anak[1][batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  return Anak

AnakCX = PMX(Induk)
print("Anak :",AnakCX)

Anak : [[3 1 7 8 5 6 9 0 2 4]
 [0 5 9 6 2 1 8 3 1 7]]


In [50]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)

  I1rs1 = Induk [0][r1]
  I1rs2 = Induk [0][r2]
  I2rs1 = Induk [1][r1]
  I2rs2 = Induk [1][r2] 

  Anak [0][r1] = I1rs2
  Anak [0][r2] = I1rs1
  Anak [1][r1] = I2rs2  
  Anak [1][r2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[3 1 7 8 5 6 9 0 2 4]
 [0 5 9 6 2 1 8 3 1 7]]
AnakM : [[0 1 7 8 5 6 9 3 2 4]
 [3 5 9 6 2 1 8 0 1 7]]


In [51]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)
  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]

  return [P,fitP]

fitAnak= fungsiObjectif(AnakM,daftarKota)
print(P)
print(AnakM)
print(fitP)
print(fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print(P)
print(fitP)

[[2 9 1 6 4 5 3 0 7 8]
 [0 5 9 6 2 1 8 4 7 3]
 [3 1 7 8 5 6 9 0 4 2]
 [7 2 0 5 4 6 1 9 3 8]]
[[0 1 7 8 5 6 9 3 2 4]
 [3 5 9 6 2 1 8 0 1 7]]
[277.36073072 234.83039887 277.68911658 221.00217053]
[236.14943774 259.10698706]
[array([[3, 5, 9, 6, 2, 1, 8, 0, 1, 7],
       [0, 5, 9, 6, 2, 1, 8, 4, 7, 3],
       [0, 1, 7, 8, 5, 6, 9, 3, 2, 4],
       [7, 2, 0, 5, 4, 6, 1, 9, 3, 8]]), array([259.10698706, 234.83039887, 236.14943774, 221.00217053])]
[259.10698706 234.83039887 236.14943774 221.00217053]


In [53]:
# Inisialisasi paramater
PCX = 0.95
Pm = 0.01
ukuranPopulasi = 4
max_generasi = 10

# Inisialisasi populasi 

P = initPopulasi (ukuranPopulasi,jumlahKota)
print("P0 :",P)

#melakukan evaluasi P
fitP = fungsiObjectif(P,daftarKota)
print("fitness populasi awal:",fitP)

print("fitness terbaik awal:",fitP.min())
print("rute awal :",P[fitP.argmin()])


for i in range(max_generasi):
  print("generasi :",i)
  Induk = seleksi(P,fitP)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)
    #print("AnakXO :",Anak)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)
      #print("AnakR :",Anak)

  fitAnak = fungsiObjectif(Anak,daftarKota)
  #print("fitAnak :",fitAnak)

  print("fitness:",fitAnak.min())

  [P, fitP]= Elitism (P,Anak,fitP,fitAnak)   
  
print("fitness populasi akhir:",fitP)
print("fitness akhir:",fitP.min())
print("rute akhir :",P[fitP.argmin()])

P0 : [[4 9 7 5 1 3 8 2 6 0]
 [6 4 1 9 0 5 3 8 2 7]
 [7 4 2 9 3 0 5 6 8 1]
 [4 0 9 2 7 1 3 5 6 8]]
fitness populasi awal: [186.84347321 261.63628978 228.35788319 244.14648901]
fitness terbaik awal: 186.84347320504725
rute awal : [4 9 7 5 1 3 8 2 6 0]
generasi : 0
fitness: 186.84347320504725
generasi : 1
fitness: 186.84347320504725
generasi : 2
fitness: 175.894271688517
generasi : 3
fitness: 175.894271688517
generasi : 4
fitness: 163.8497055899237
generasi : 5
fitness: 140.92077340178918
generasi : 6
fitness: 152.68252884172742
generasi : 7
fitness: 140.92077340178918
generasi : 8
fitness: 95.36733657606395
generasi : 9
fitness: 112.63650215432727
fitness populasi akhir: [112.63650215 112.63650215  95.36733658 112.63650215]
fitness akhir: 95.36733657606395
rute akhir : [4 9 7 5 0 0 0 0 0 0]
